project_id = "ctunsjfxwwtlnvusmkxb"

[functions.available-timeslots]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.send-email-broadcast]
verify_jwt = true